name: MiroToSentinel_$(Build.BuildId)

trigger:
  branches:
    include: [main, master]

stages:
  -
    stage: build
    displayName: Build
    condition: eq(variables['Build.Reason'], 'PullRequest')
    pool:
      vmImage: ubuntu-latest
    jobs:
      -
        job: mirotosen_build
        steps:
          -
            task: GoTool@0
            displayName: "Install Go"
            inputs:
              version: '1.22.1'
          -
            script: |
              go build -o /dev/null ./cmd/...
            displayName: 'Build miro2sen'

  -
    stage: test
    displayName: Test
    condition: eq(variables['Build.Reason'], 'PullRequest')
    pool:
      vmImage: ubuntu-latest
    jobs:
      -
        job: mirotosen_build
        steps:
          -
            task: GoTool@0
            displayName: "Install Go"
            inputs: