name: MiroToSentinel_$(Build.BuildId)

trigger:
  branches:
    include: [main, master]

schedules:
-
  cron: '0 * * * *'
  displayName: 'Hourly run of the Miro to SIEM ingestor'
  branches:
    include: [ main ]
  always: true

stages:
-
  stage: run
  displayName: Ingest miro logs to Sentinel
  condition: ne(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: ubuntu-latest
  jobs:
  -
    job: mirotosen_run
    steps:
    -
      task: GoTool@0
      inputs:
        version: '1.22.1'
      displayName: "Install Go"
    -
      task: DownloadSecureFile@1
      name: config
      inputs:
        secureFile: miro2sentinel_config.yml
      displayName: "Download config file"
    -
      script: |
        go run ./cmd/... -config=$(config.secureFilePath)
      displayName: 'Run miro ingestor'
      retryCountOnTaskFailure: 3